@startuml
'https://plantuml.com/class-diagram


Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

class Game {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml